// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"dax/server/ent/entry"
	"dax/server/ent/predicate"
	"dax/server/ent/vault"
	"dax/server/lib/types"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EntryUpdate is the builder for updating Entry entities.
type EntryUpdate struct {
	config
	hooks    []Hook
	mutation *EntryMutation
}

// Where appends a list predicates to the EntryUpdate builder.
func (_u *EntryUpdate) Where(ps ...predicate.Entry) *EntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetHeading sets the "heading" field.
func (_u *EntryUpdate) SetHeading(v string) *EntryUpdate {
	_u.mutation.SetHeading(v)
	return _u
}

// SetNillableHeading sets the "heading" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableHeading(v *string) *EntryUpdate {
	if v != nil {
		_u.SetHeading(*v)
	}
	return _u
}

// ClearHeading clears the value of the "heading" field.
func (_u *EntryUpdate) ClearHeading() *EntryUpdate {
	_u.mutation.ClearHeading()
	return _u
}

// SetBody sets the "body" field.
func (_u *EntryUpdate) SetBody(v string) *EntryUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableBody(v *string) *EntryUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *EntryUpdate) ClearBody() *EntryUpdate {
	_u.mutation.ClearBody()
	return _u
}

// SetAttributes sets the "attributes" field.
func (_u *EntryUpdate) SetAttributes(v types.JSON) *EntryUpdate {
	_u.mutation.SetAttributes(v)
	return _u
}

// ClearAttributes clears the value of the "attributes" field.
func (_u *EntryUpdate) ClearAttributes() *EntryUpdate {
	_u.mutation.ClearAttributes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EntryUpdate) SetUpdatedAt(v time.Time) *EntryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetVaultID sets the "vault" edge to the Vault entity by ID.
func (_u *EntryUpdate) SetVaultID(id int) *EntryUpdate {
	_u.mutation.SetVaultID(id)
	return _u
}

// SetNillableVaultID sets the "vault" edge to the Vault entity by ID if the given value is not nil.
func (_u *EntryUpdate) SetNillableVaultID(id *int) *EntryUpdate {
	if id != nil {
		_u = _u.SetVaultID(*id)
	}
	return _u
}

// SetVault sets the "vault" edge to the Vault entity.
func (_u *EntryUpdate) SetVault(v *Vault) *EntryUpdate {
	return _u.SetVaultID(v.ID)
}

// Mutation returns the EntryMutation object of the builder.
func (_u *EntryUpdate) Mutation() *EntryMutation {
	return _u.mutation
}

// ClearVault clears the "vault" edge to the Vault entity.
func (_u *EntryUpdate) ClearVault() *EntryUpdate {
	_u.mutation.ClearVault()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EntryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := entry.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *EntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(entry.Table, entry.Columns, sqlgraph.NewFieldSpec(entry.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Heading(); ok {
		_spec.SetField(entry.FieldHeading, field.TypeString, value)
	}
	if _u.mutation.HeadingCleared() {
		_spec.ClearField(entry.FieldHeading, field.TypeString)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(entry.FieldBody, field.TypeString, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(entry.FieldBody, field.TypeString)
	}
	if value, ok := _u.mutation.Attributes(); ok {
		_spec.SetField(entry.FieldAttributes, field.TypeJSON, value)
	}
	if _u.mutation.AttributesCleared() {
		_spec.ClearField(entry.FieldAttributes, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entry.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.VaultCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entry.VaultTable,
			Columns: []string{entry.VaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vault.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VaultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entry.VaultTable,
			Columns: []string{entry.VaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vault.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EntryUpdateOne is the builder for updating a single Entry entity.
type EntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EntryMutation
}

// SetHeading sets the "heading" field.
func (_u *EntryUpdateOne) SetHeading(v string) *EntryUpdateOne {
	_u.mutation.SetHeading(v)
	return _u
}

// SetNillableHeading sets the "heading" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableHeading(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetHeading(*v)
	}
	return _u
}

// ClearHeading clears the value of the "heading" field.
func (_u *EntryUpdateOne) ClearHeading() *EntryUpdateOne {
	_u.mutation.ClearHeading()
	return _u
}

// SetBody sets the "body" field.
func (_u *EntryUpdateOne) SetBody(v string) *EntryUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableBody(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *EntryUpdateOne) ClearBody() *EntryUpdateOne {
	_u.mutation.ClearBody()
	return _u
}

// SetAttributes sets the "attributes" field.
func (_u *EntryUpdateOne) SetAttributes(v types.JSON) *EntryUpdateOne {
	_u.mutation.SetAttributes(v)
	return _u
}

// ClearAttributes clears the value of the "attributes" field.
func (_u *EntryUpdateOne) ClearAttributes() *EntryUpdateOne {
	_u.mutation.ClearAttributes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EntryUpdateOne) SetUpdatedAt(v time.Time) *EntryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetVaultID sets the "vault" edge to the Vault entity by ID.
func (_u *EntryUpdateOne) SetVaultID(id int) *EntryUpdateOne {
	_u.mutation.SetVaultID(id)
	return _u
}

// SetNillableVaultID sets the "vault" edge to the Vault entity by ID if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableVaultID(id *int) *EntryUpdateOne {
	if id != nil {
		_u = _u.SetVaultID(*id)
	}
	return _u
}

// SetVault sets the "vault" edge to the Vault entity.
func (_u *EntryUpdateOne) SetVault(v *Vault) *EntryUpdateOne {
	return _u.SetVaultID(v.ID)
}

// Mutation returns the EntryMutation object of the builder.
func (_u *EntryUpdateOne) Mutation() *EntryMutation {
	return _u.mutation
}

// ClearVault clears the "vault" edge to the Vault entity.
func (_u *EntryUpdateOne) ClearVault() *EntryUpdateOne {
	_u.mutation.ClearVault()
	return _u
}

// Where appends a list predicates to the EntryUpdate builder.
func (_u *EntryUpdateOne) Where(ps ...predicate.Entry) *EntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EntryUpdateOne) Select(field string, fields ...string) *EntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Entry entity.
func (_u *EntryUpdateOne) Save(ctx context.Context) (*Entry, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntryUpdateOne) SaveX(ctx context.Context) *Entry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := entry.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *EntryUpdateOne) sqlSave(ctx context.Context) (_node *Entry, err error) {
	_spec := sqlgraph.NewUpdateSpec(entry.Table, entry.Columns, sqlgraph.NewFieldSpec(entry.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Entry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entry.FieldID)
		for _, f := range fields {
			if !entry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Heading(); ok {
		_spec.SetField(entry.FieldHeading, field.TypeString, value)
	}
	if _u.mutation.HeadingCleared() {
		_spec.ClearField(entry.FieldHeading, field.TypeString)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(entry.FieldBody, field.TypeString, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(entry.FieldBody, field.TypeString)
	}
	if value, ok := _u.mutation.Attributes(); ok {
		_spec.SetField(entry.FieldAttributes, field.TypeJSON, value)
	}
	if _u.mutation.AttributesCleared() {
		_spec.ClearField(entry.FieldAttributes, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entry.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.VaultCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entry.VaultTable,
			Columns: []string{entry.VaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vault.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VaultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entry.VaultTable,
			Columns: []string{entry.VaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vault.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Entry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
