// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"dax/server/ent/entry"
	"dax/server/ent/vault"
	"dax/server/lib/types"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EntryCreate is the builder for creating a Entry entity.
type EntryCreate struct {
	config
	mutation *EntryMutation
	hooks    []Hook
}

// SetHeading sets the "heading" field.
func (_c *EntryCreate) SetHeading(v string) *EntryCreate {
	_c.mutation.SetHeading(v)
	return _c
}

// SetNillableHeading sets the "heading" field if the given value is not nil.
func (_c *EntryCreate) SetNillableHeading(v *string) *EntryCreate {
	if v != nil {
		_c.SetHeading(*v)
	}
	return _c
}

// SetBody sets the "body" field.
func (_c *EntryCreate) SetBody(v string) *EntryCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_c *EntryCreate) SetNillableBody(v *string) *EntryCreate {
	if v != nil {
		_c.SetBody(*v)
	}
	return _c
}

// SetAttributes sets the "attributes" field.
func (_c *EntryCreate) SetAttributes(v types.JSON) *EntryCreate {
	_c.mutation.SetAttributes(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EntryCreate) SetCreatedAt(v time.Time) *EntryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EntryCreate) SetNillableCreatedAt(v *time.Time) *EntryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EntryCreate) SetUpdatedAt(v time.Time) *EntryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetVaultID sets the "vault" edge to the Vault entity by ID.
func (_c *EntryCreate) SetVaultID(id int) *EntryCreate {
	_c.mutation.SetVaultID(id)
	return _c
}

// SetNillableVaultID sets the "vault" edge to the Vault entity by ID if the given value is not nil.
func (_c *EntryCreate) SetNillableVaultID(id *int) *EntryCreate {
	if id != nil {
		_c = _c.SetVaultID(*id)
	}
	return _c
}

// SetVault sets the "vault" edge to the Vault entity.
func (_c *EntryCreate) SetVault(v *Vault) *EntryCreate {
	return _c.SetVaultID(v.ID)
}

// Mutation returns the EntryMutation object of the builder.
func (_c *EntryCreate) Mutation() *EntryMutation {
	return _c.mutation
}

// Save creates the Entry in the database.
func (_c *EntryCreate) Save(ctx context.Context) (*Entry, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EntryCreate) SaveX(ctx context.Context) *Entry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EntryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := entry.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EntryCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Entry.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Entry.updated_at"`)}
	}
	return nil
}

func (_c *EntryCreate) sqlSave(ctx context.Context) (*Entry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EntryCreate) createSpec() (*Entry, *sqlgraph.CreateSpec) {
	var (
		_node = &Entry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(entry.Table, sqlgraph.NewFieldSpec(entry.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Heading(); ok {
		_spec.SetField(entry.FieldHeading, field.TypeString, value)
		_node.Heading = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(entry.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.Attributes(); ok {
		_spec.SetField(entry.FieldAttributes, field.TypeJSON, value)
		_node.Attributes = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(entry.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(entry.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.VaultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entry.VaultTable,
			Columns: []string{entry.VaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vault.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.vault_entries = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EntryCreateBulk is the builder for creating many Entry entities in bulk.
type EntryCreateBulk struct {
	config
	err      error
	builders []*EntryCreate
}

// Save creates the Entry entities in the database.
func (_c *EntryCreateBulk) Save(ctx context.Context) ([]*Entry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Entry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EntryCreateBulk) SaveX(ctx context.Context) []*Entry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
