// Code generated by ent, DO NOT EDIT.

package ent

import (
	"dax/server/lib/types"
	"time"
)

// CreateEntryInput represents a mutation input for creating entries.
type CreateEntryInput struct {
	Heading    *string
	Body       *string
	Attributes types.JSON
	CreatedAt  *time.Time
	UpdatedAt  time.Time
	VaultID    *int
}

// Mutate applies the CreateEntryInput on the EntryMutation builder.
func (i *CreateEntryInput) Mutate(m *EntryMutation) {
	if v := i.Heading; v != nil {
		m.SetHeading(*v)
	}
	if v := i.Body; v != nil {
		m.SetBody(*v)
	}
	if v := i.Attributes; v != nil {
		m.SetAttributes(v)
	}
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	m.SetUpdatedAt(i.UpdatedAt)
	if v := i.VaultID; v != nil {
		m.SetVaultID(*v)
	}
}

// SetInput applies the change-set in the CreateEntryInput on the EntryCreate builder.
func (c *EntryCreate) SetInput(i CreateEntryInput) *EntryCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateEntryInput represents a mutation input for updating entries.
type UpdateEntryInput struct {
	ClearHeading    bool
	Heading         *string
	ClearBody       bool
	Body            *string
	ClearAttributes bool
	Attributes      types.JSON
	UpdatedAt       *time.Time
	ClearVault      bool
	VaultID         *int
}

// Mutate applies the UpdateEntryInput on the EntryMutation builder.
func (i *UpdateEntryInput) Mutate(m *EntryMutation) {
	if i.ClearHeading {
		m.ClearHeading()
	}
	if v := i.Heading; v != nil {
		m.SetHeading(*v)
	}
	if i.ClearBody {
		m.ClearBody()
	}
	if v := i.Body; v != nil {
		m.SetBody(*v)
	}
	if i.ClearAttributes {
		m.ClearAttributes()
	}
	if v := i.Attributes; v != nil {
		m.SetAttributes(v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if i.ClearVault {
		m.ClearVault()
	}
	if v := i.VaultID; v != nil {
		m.SetVaultID(*v)
	}
}

// SetInput applies the change-set in the UpdateEntryInput on the EntryUpdate builder.
func (c *EntryUpdate) SetInput(i UpdateEntryInput) *EntryUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateEntryInput on the EntryUpdateOne builder.
func (c *EntryUpdateOne) SetInput(i UpdateEntryInput) *EntryUpdateOne {
	i.Mutate(c.Mutation())
	return c
}

// UpdateUserInput represents a mutation input for updating users.
type UpdateUserInput struct {
	Username       *string
	Hash           *string
	ClearSettings  bool
	Settings       types.JSON
	ActiveAt       *time.Time
	ClearVaults    bool
	AddVaultIDs    []int
	RemoveVaultIDs []int
}

// Mutate applies the UpdateUserInput on the UserMutation builder.
func (i *UpdateUserInput) Mutate(m *UserMutation) {
	if v := i.Username; v != nil {
		m.SetUsername(*v)
	}
	if v := i.Hash; v != nil {
		m.SetHash(*v)
	}
	if i.ClearSettings {
		m.ClearSettings()
	}
	if v := i.Settings; v != nil {
		m.SetSettings(v)
	}
	if v := i.ActiveAt; v != nil {
		m.SetActiveAt(*v)
	}
	if i.ClearVaults {
		m.ClearVaults()
	}
	if v := i.AddVaultIDs; len(v) > 0 {
		m.AddVaultIDs(v...)
	}
	if v := i.RemoveVaultIDs; len(v) > 0 {
		m.RemoveVaultIDs(v...)
	}
}

// SetInput applies the change-set in the UpdateUserInput on the UserUpdate builder.
func (c *UserUpdate) SetInput(i UpdateUserInput) *UserUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateUserInput on the UserUpdateOne builder.
func (c *UserUpdateOne) SetInput(i UpdateUserInput) *UserUpdateOne {
	i.Mutate(c.Mutation())
	return c
}

// CreateVaultInput represents a mutation input for creating vaults.
type CreateVaultInput struct {
	Name      string
	Settings  types.JSON
	CreatedAt *time.Time
	UserIDs   []int
	EntryIDs  []int
}

// Mutate applies the CreateVaultInput on the VaultMutation builder.
func (i *CreateVaultInput) Mutate(m *VaultMutation) {
	m.SetName(i.Name)
	if v := i.Settings; v != nil {
		m.SetSettings(v)
	}
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UserIDs; len(v) > 0 {
		m.AddUserIDs(v...)
	}
	if v := i.EntryIDs; len(v) > 0 {
		m.AddEntryIDs(v...)
	}
}

// SetInput applies the change-set in the CreateVaultInput on the VaultCreate builder.
func (c *VaultCreate) SetInput(i CreateVaultInput) *VaultCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateVaultInput represents a mutation input for updating vaults.
type UpdateVaultInput struct {
	Name           *string
	ClearSettings  bool
	Settings       types.JSON
	ClearUsers     bool
	AddUserIDs     []int
	RemoveUserIDs  []int
	ClearEntries   bool
	AddEntryIDs    []int
	RemoveEntryIDs []int
}

// Mutate applies the UpdateVaultInput on the VaultMutation builder.
func (i *UpdateVaultInput) Mutate(m *VaultMutation) {
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if i.ClearSettings {
		m.ClearSettings()
	}
	if v := i.Settings; v != nil {
		m.SetSettings(v)
	}
	if i.ClearUsers {
		m.ClearUsers()
	}
	if v := i.AddUserIDs; len(v) > 0 {
		m.AddUserIDs(v...)
	}
	if v := i.RemoveUserIDs; len(v) > 0 {
		m.RemoveUserIDs(v...)
	}
	if i.ClearEntries {
		m.ClearEntries()
	}
	if v := i.AddEntryIDs; len(v) > 0 {
		m.AddEntryIDs(v...)
	}
	if v := i.RemoveEntryIDs; len(v) > 0 {
		m.RemoveEntryIDs(v...)
	}
}

// SetInput applies the change-set in the UpdateVaultInput on the VaultUpdate builder.
func (c *VaultUpdate) SetInput(i UpdateVaultInput) *VaultUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateVaultInput on the VaultUpdateOne builder.
func (c *VaultUpdateOne) SetInput(i UpdateVaultInput) *VaultUpdateOne {
	i.Mutate(c.Mutation())
	return c
}
