// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (_m *Entry) Vault(ctx context.Context) (*Vault, error) {
	result, err := _m.Edges.VaultOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryVault().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *User) Vaults(ctx context.Context) (result []*Vault, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedVaults(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.VaultsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryVaults().All(ctx)
	}
	return result, err
}

func (_m *Vault) Users(ctx context.Context) (result []*User, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedUsers(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.UsersOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryUsers().All(ctx)
	}
	return result, err
}

func (_m *Vault) Entries(ctx context.Context) (result []*Entry, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedEntries(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.EntriesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryEntries().All(ctx)
	}
	return result, err
}
