// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"dax/server/ent/entry"
	"dax/server/ent/user"
	"dax/server/ent/vault"

	"github.com/99designs/gqlgen/graphql"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *EntryQuery) CollectFields(ctx context.Context, satisfies ...string) (*EntryQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *EntryQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(entry.Columns))
		selectedFields = []string{entry.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "vault":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&VaultClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, vaultImplementors)...); err != nil {
				return err
			}
			_q.withVault = query
		case "heading":
			if _, ok := fieldSeen[entry.FieldHeading]; !ok {
				selectedFields = append(selectedFields, entry.FieldHeading)
				fieldSeen[entry.FieldHeading] = struct{}{}
			}
		case "body":
			if _, ok := fieldSeen[entry.FieldBody]; !ok {
				selectedFields = append(selectedFields, entry.FieldBody)
				fieldSeen[entry.FieldBody] = struct{}{}
			}
		case "attributes":
			if _, ok := fieldSeen[entry.FieldAttributes]; !ok {
				selectedFields = append(selectedFields, entry.FieldAttributes)
				fieldSeen[entry.FieldAttributes] = struct{}{}
			}
		case "createdAt":
			if _, ok := fieldSeen[entry.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, entry.FieldCreatedAt)
				fieldSeen[entry.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[entry.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, entry.FieldUpdatedAt)
				fieldSeen[entry.FieldUpdatedAt] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type entryPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []EntryPaginateOption
}

func newEntryPaginateArgs(rv map[string]any) *entryPaginateArgs {
	args := &entryPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*EntryWhereInput); ok {
		args.opts = append(args.opts, WithEntryFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *UserQuery) CollectFields(ctx context.Context, satisfies ...string) (*UserQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *UserQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(user.Columns))
		selectedFields = []string{user.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "vaults":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&VaultClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, vaultImplementors)...); err != nil {
				return err
			}
			_q.WithNamedVaults(alias, func(wq *VaultQuery) {
				*wq = *query
			})
		case "username":
			if _, ok := fieldSeen[user.FieldUsername]; !ok {
				selectedFields = append(selectedFields, user.FieldUsername)
				fieldSeen[user.FieldUsername] = struct{}{}
			}
		case "settings":
			if _, ok := fieldSeen[user.FieldSettings]; !ok {
				selectedFields = append(selectedFields, user.FieldSettings)
				fieldSeen[user.FieldSettings] = struct{}{}
			}
		case "createdAt":
			if _, ok := fieldSeen[user.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, user.FieldCreatedAt)
				fieldSeen[user.FieldCreatedAt] = struct{}{}
			}
		case "activeAt":
			if _, ok := fieldSeen[user.FieldActiveAt]; !ok {
				selectedFields = append(selectedFields, user.FieldActiveAt)
				fieldSeen[user.FieldActiveAt] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type userPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []UserPaginateOption
}

func newUserPaginateArgs(rv map[string]any) *userPaginateArgs {
	args := &userPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*UserWhereInput); ok {
		args.opts = append(args.opts, WithUserFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *VaultQuery) CollectFields(ctx context.Context, satisfies ...string) (*VaultQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *VaultQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(vault.Columns))
		selectedFields = []string{vault.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "users":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&UserClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, userImplementors)...); err != nil {
				return err
			}
			_q.WithNamedUsers(alias, func(wq *UserQuery) {
				*wq = *query
			})

		case "entries":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&EntryClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, entryImplementors)...); err != nil {
				return err
			}
			_q.WithNamedEntries(alias, func(wq *EntryQuery) {
				*wq = *query
			})
		case "name":
			if _, ok := fieldSeen[vault.FieldName]; !ok {
				selectedFields = append(selectedFields, vault.FieldName)
				fieldSeen[vault.FieldName] = struct{}{}
			}
		case "settings":
			if _, ok := fieldSeen[vault.FieldSettings]; !ok {
				selectedFields = append(selectedFields, vault.FieldSettings)
				fieldSeen[vault.FieldSettings] = struct{}{}
			}
		case "createdAt":
			if _, ok := fieldSeen[vault.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, vault.FieldCreatedAt)
				fieldSeen[vault.FieldCreatedAt] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type vaultPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []VaultPaginateOption
}

func newVaultPaginateArgs(rv map[string]any) *vaultPaginateArgs {
	args := &vaultPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*VaultWhereInput); ok {
		args.opts = append(args.opts, WithVaultFilter(v.Filter))
	}
	return args
}

const (
	afterField     = "after"
	firstField     = "first"
	beforeField    = "before"
	lastField      = "last"
	orderByField   = "orderBy"
	directionField = "direction"
	fieldField     = "field"
	whereField     = "where"
)

func fieldArgs(ctx context.Context, whereInput any, path ...string) map[string]any {
	field := collectedField(ctx, path...)
	if field == nil || field.Arguments == nil {
		return nil
	}
	oc := graphql.GetOperationContext(ctx)
	args := field.ArgumentMap(oc.Variables)
	return unmarshalArgs(ctx, whereInput, args)
}

// unmarshalArgs allows extracting the field arguments from their raw representation.
func unmarshalArgs(ctx context.Context, whereInput any, args map[string]any) map[string]any {
	for _, k := range []string{firstField, lastField} {
		v, ok := args[k]
		if !ok || v == nil {
			continue
		}
		i, err := graphql.UnmarshalInt(v)
		if err == nil {
			args[k] = &i
		}
	}
	for _, k := range []string{beforeField, afterField} {
		v, ok := args[k]
		if !ok {
			continue
		}
		c := &Cursor{}
		if c.UnmarshalGQL(v) == nil {
			args[k] = c
		}
	}
	if v, ok := args[whereField]; ok && whereInput != nil {
		if err := graphql.UnmarshalInputFromContext(ctx, v, whereInput); err == nil {
			args[whereField] = whereInput
		}
	}

	return args
}

// mayAddCondition appends another type condition to the satisfies list
// if it does not exist in the list.
func mayAddCondition(satisfies []string, typeCond []string) []string {
Cond:
	for _, c := range typeCond {
		for _, s := range satisfies {
			if c == s {
				continue Cond
			}
		}
		satisfies = append(satisfies, c)
	}
	return satisfies
}
