// Code generated by ent, DO NOT EDIT.

package ent

import (
	"dax/server/ent/entry"
	"dax/server/ent/schema"
	"dax/server/ent/user"
	"dax/server/ent/vault"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	entryFields := schema.Entry{}.Fields()
	_ = entryFields
	// entryDescCreatedAt is the schema descriptor for created_at field.
	entryDescCreatedAt := entryFields[3].Descriptor()
	// entry.DefaultCreatedAt holds the default value on creation for the created_at field.
	entry.DefaultCreatedAt = entryDescCreatedAt.Default.(func() time.Time)
	// entryDescUpdatedAt is the schema descriptor for updated_at field.
	entryDescUpdatedAt := entryFields[4].Descriptor()
	// entry.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	entry.UpdateDefaultUpdatedAt = entryDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	vaultFields := schema.Vault{}.Fields()
	_ = vaultFields
	// vaultDescCreatedAt is the schema descriptor for created_at field.
	vaultDescCreatedAt := vaultFields[2].Descriptor()
	// vault.DefaultCreatedAt holds the default value on creation for the created_at field.
	vault.DefaultCreatedAt = vaultDescCreatedAt.Default.(func() time.Time)
}
