-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.ent_types
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    type character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT ent_types_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.entries
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    heading character varying COLLATE pg_catalog."default",
    body text COLLATE pg_catalog."default",
    attributes jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    vault_entries bigint,
    CONSTRAINT entries_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_vaults
(
    user_id bigint NOT NULL,
    vault_id bigint NOT NULL,
    CONSTRAINT user_vaults_pkey PRIMARY KEY (user_id, vault_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 4294967296 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    username character varying COLLATE pg_catalog."default" NOT NULL,
    hash character varying COLLATE pg_catalog."default" NOT NULL,
    settings jsonb,
    created_at timestamp with time zone NOT NULL,
    active_at timestamp with time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.vaults
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 8589934592 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    settings jsonb,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT vaults_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.entries
    ADD CONSTRAINT entries_vaults_entries FOREIGN KEY (vault_entries)
    REFERENCES public.vaults (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.user_vaults
    ADD CONSTRAINT user_vaults_user_id FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_vaults
    ADD CONSTRAINT user_vaults_vault_id FOREIGN KEY (vault_id)
    REFERENCES public.vaults (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;