# Generated by Django 6.0 on 2025-12-17 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='vault name')),
                ('settings', models.JSONField(default=dict, verbose_name='vault settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_vaults', to=settings.AUTH_USER_MODEL, verbose_name='vault owner')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255, verbose_name='entry heading')),
                ('body', models.TextField(verbose_name='entry body')),
                ('attributes', models.JSONField(default=dict, verbose_name='entry attributes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dax.vault')),
            ],
        ),
        migrations.CreateModel(
            name='VaultUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='vault contributor')),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dax.vault')),
            ],
            options={
                'db_table': 'dax_vault_user',
            },
        ),
        migrations.AddField(
            model_name='vault',
            name='contributors',
            field=models.ManyToManyField(related_name='contributed_vaults', through='dax.VaultUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='vaultuser',
            constraint=models.UniqueConstraint(fields=('vault', 'user'), name='unique_vault_user'),
        ),
    ]
