# Generated by Django 6.0 on 2025-12-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='entry attributes'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=models.TextField(blank=True, verbose_name='entry body'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='entry heading'),
        ),
        migrations.AlterField(
            model_name='vault',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='vault name'),
        ),
        migrations.AlterField(
            model_name='vault',
            name='settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='vault settings'),
        ),
    ]
