# Generated by Django 6.0 on 2025-12-17 23:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dax', '0002_alter_entry_attributes_alter_entry_body_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='name',
            field=models.CharField(max_length=255, verbose_name='vault name'),
        ),
        migrations.AddConstraint(
            model_name='vault',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_vault_name_per_owner'),
        ),
    ]
