// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Entry is the predicate function for entry builders.
type Entry func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Vault is the predicate function for vault builders.
type Vault func(*sql.Selector)
