-- Table definitions for dax_entry and dax_vault

CREATE TABLE public.dax_vault (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    settings jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE public.dax_entry (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    heading character varying(255) NOT NULL,
    body text NOT NULL,
    attributes jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    vault_id bigint NOT NULL
);
