-- Table definitions for dax_entry and dax_vault

CREATE TABLE public.dax_vault (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255),
    settings jsonb,
    created_at timestamp with time zone NOT NULL,
    owner_id uuid NOT NULL,
    transient_client_id uuid, -- temp id provided by frontentend client for realtime change notification filtering
    CONSTRAINT dax_vault_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE TABLE public.dax_entry (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    heading character varying(255),
    body text,
    body_tsvector tsvector GENERATED ALWAYS AS (to_tsvector('english', coalesce(body, ''))) STORED,
    attributes jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    vault_id bigint NOT NULL,
    transient_client_id uuid, -- temp id provided by frontentend client for realtime change notification filtering
    CONSTRAINT dax_entry_vault_id_fkey FOREIGN KEY (vault_id) REFERENCES dax_vault(id) ON DELETE CASCADE
);
