package main

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"dax/server/ent"
	"fmt"
)

// Attributes is the resolver for the attributes field.
func (r *entryResolver) Attributes(ctx context.Context, obj *ent.Entry) (map[string]any, error) {
	panic(fmt.Errorf("not implemented: Attributes - attributes"))
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id int) (ent.Noder, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []int) ([]ent.Noder, error) {
	panic(fmt.Errorf("not implemented: Nodes - nodes"))
}

// Entries is the resolver for the entries field.
func (r *queryResolver) Entries(ctx context.Context) ([]*ent.Entry, error) {
	panic(fmt.Errorf("not implemented: Entries - entries"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*ent.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// Vaults is the resolver for the vaults field.
func (r *queryResolver) Vaults(ctx context.Context) ([]*ent.Vault, error) {
	panic(fmt.Errorf("not implemented: Vaults - vaults"))
}

// Settings is the resolver for the settings field.
func (r *userResolver) Settings(ctx context.Context, obj *ent.User) (map[string]any, error) {
	panic(fmt.Errorf("not implemented: Settings - settings"))
}

// Settings is the resolver for the settings field.
func (r *vaultResolver) Settings(ctx context.Context, obj *ent.Vault) (map[string]any, error) {
	panic(fmt.Errorf("not implemented: Settings - settings"))
}

// Attributes is the resolver for the attributes field.
func (r *createEntryInputResolver) Attributes(ctx context.Context, obj *ent.CreateEntryInput, data map[string]any) error {
	panic(fmt.Errorf("not implemented: Attributes - attributes"))
}

// Settings is the resolver for the settings field.
func (r *createVaultInputResolver) Settings(ctx context.Context, obj *ent.CreateVaultInput, data map[string]any) error {
	panic(fmt.Errorf("not implemented: Settings - settings"))
}

// Attributes is the resolver for the attributes field.
func (r *updateEntryInputResolver) Attributes(ctx context.Context, obj *ent.UpdateEntryInput, data map[string]any) error {
	panic(fmt.Errorf("not implemented: Attributes - attributes"))
}

// Settings is the resolver for the settings field.
func (r *updateUserInputResolver) Settings(ctx context.Context, obj *ent.UpdateUserInput, data map[string]any) error {
	panic(fmt.Errorf("not implemented: Settings - settings"))
}

// Settings is the resolver for the settings field.
func (r *updateVaultInputResolver) Settings(ctx context.Context, obj *ent.UpdateVaultInput, data map[string]any) error {
	panic(fmt.Errorf("not implemented: Settings - settings"))
}

// Entry returns EntryResolver implementation.
func (r *Resolver) Entry() EntryResolver { return &entryResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

// Vault returns VaultResolver implementation.
func (r *Resolver) Vault() VaultResolver { return &vaultResolver{r} }

// CreateEntryInput returns CreateEntryInputResolver implementation.
func (r *Resolver) CreateEntryInput() CreateEntryInputResolver { return &createEntryInputResolver{r} }

// CreateVaultInput returns CreateVaultInputResolver implementation.
func (r *Resolver) CreateVaultInput() CreateVaultInputResolver { return &createVaultInputResolver{r} }

// UpdateEntryInput returns UpdateEntryInputResolver implementation.
func (r *Resolver) UpdateEntryInput() UpdateEntryInputResolver { return &updateEntryInputResolver{r} }

// UpdateUserInput returns UpdateUserInputResolver implementation.
func (r *Resolver) UpdateUserInput() UpdateUserInputResolver { return &updateUserInputResolver{r} }

// UpdateVaultInput returns UpdateVaultInputResolver implementation.
func (r *Resolver) UpdateVaultInput() UpdateVaultInputResolver { return &updateVaultInputResolver{r} }

type entryResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
type vaultResolver struct{ *Resolver }
type createEntryInputResolver struct{ *Resolver }
type createVaultInputResolver struct{ *Resolver }
type updateEntryInputResolver struct{ *Resolver }
type updateUserInputResolver struct{ *Resolver }
type updateVaultInputResolver struct{ *Resolver }
