// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EntriesColumns holds the columns for the "entries" table.
	EntriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "heading", Type: field.TypeString, Nullable: true},
		{Name: "body", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "attributes", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "vault_entries", Type: field.TypeInt, Nullable: true},
	}
	// EntriesTable holds the schema information for the "entries" table.
	EntriesTable = &schema.Table{
		Name:       "entries",
		Columns:    EntriesColumns,
		PrimaryKey: []*schema.Column{EntriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "entries_vaults_entries",
				Columns:    []*schema.Column{EntriesColumns[6]},
				RefColumns: []*schema.Column{VaultsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "entry_heading",
				Unique:  false,
				Columns: []*schema.Column{EntriesColumns[1]},
				Annotation: &entsql.IndexAnnotation{
					OpClass: "gin_trgm_ops",
					Types: map[string]string{
						"postgres": "GIN",
					},
				},
			},
			{
				Name:    "entry_created_at",
				Unique:  false,
				Columns: []*schema.Column{EntriesColumns[4]},
				Annotation: &entsql.IndexAnnotation{
					Desc: true,
				},
			},
			{
				Name:    "entry_updated_at",
				Unique:  false,
				Columns: []*schema.Column{EntriesColumns[5]},
				Annotation: &entsql.IndexAnnotation{
					Desc: true,
				},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "hash", Type: field.TypeString},
		{Name: "settings", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "active_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// VaultsColumns holds the columns for the "vaults" table.
	VaultsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "settings", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// VaultsTable holds the schema information for the "vaults" table.
	VaultsTable = &schema.Table{
		Name:       "vaults",
		Columns:    VaultsColumns,
		PrimaryKey: []*schema.Column{VaultsColumns[0]},
	}
	// UserVaultsColumns holds the columns for the "user_vaults" table.
	UserVaultsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "vault_id", Type: field.TypeInt},
	}
	// UserVaultsTable holds the schema information for the "user_vaults" table.
	UserVaultsTable = &schema.Table{
		Name:       "user_vaults",
		Columns:    UserVaultsColumns,
		PrimaryKey: []*schema.Column{UserVaultsColumns[0], UserVaultsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_vaults_user_id",
				Columns:    []*schema.Column{UserVaultsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_vaults_vault_id",
				Columns:    []*schema.Column{UserVaultsColumns[1]},
				RefColumns: []*schema.Column{VaultsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EntriesTable,
		UsersTable,
		VaultsTable,
		UserVaultsTable,
	}
)

func init() {
	EntriesTable.ForeignKeys[0].RefTable = VaultsTable
	UserVaultsTable.ForeignKeys[0].RefTable = UsersTable
	UserVaultsTable.ForeignKeys[1].RefTable = VaultsTable
}
