// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// FieldSettings holds the string denoting the settings field in the database.
	FieldSettings = "settings"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldActiveAt holds the string denoting the active_at field in the database.
	FieldActiveAt = "active_at"
	// EdgeVaults holds the string denoting the vaults edge name in mutations.
	EdgeVaults = "vaults"
	// Table holds the table name of the user in the database.
	Table = "users"
	// VaultsTable is the table that holds the vaults relation/edge. The primary key declared below.
	VaultsTable = "user_vaults"
	// VaultsInverseTable is the table name for the Vault entity.
	// It exists in this package in order to avoid circular dependency with the "vault" package.
	VaultsInverseTable = "vaults"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldHash,
	FieldSettings,
	FieldCreatedAt,
	FieldActiveAt,
}

var (
	// VaultsPrimaryKey and VaultsColumn2 are the table columns denoting the
	// primary key for the vaults relation (M2M).
	VaultsPrimaryKey = []string{"user_id", "vault_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByHash orders the results by the hash field.
func ByHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHash, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByActiveAt orders the results by the active_at field.
func ByActiveAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActiveAt, opts...).ToFunc()
}

// ByVaultsCount orders the results by vaults count.
func ByVaultsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVaultsStep(), opts...)
	}
}

// ByVaults orders the results by vaults terms.
func ByVaults(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVaultsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newVaultsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VaultsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, VaultsTable, VaultsPrimaryKey...),
	)
}
