
  create table "public"."dax_entry" (
    "id" bigint generated by default as identity not null,
    "heading" character varying(255) not null,
    "body" text not null,
    "attributes" jsonb not null,
    "created_at" timestamp with time zone not null,
    "updated_at" timestamp with time zone not null,
    "vault_id" bigint not null
      );


alter table "public"."dax_entry" enable row level security;


  create table "public"."dax_vault" (
    "id" bigint generated by default as identity not null,
    "name" character varying(255) not null,
    "settings" jsonb not null,
    "created_at" timestamp with time zone not null
      );


alter table "public"."dax_vault" enable row level security;

CREATE UNIQUE INDEX dax_entry_pkey ON public.dax_entry USING btree (id);

CREATE UNIQUE INDEX dax_vault_pkey ON public.dax_vault USING btree (id);

alter table "public"."dax_entry" add constraint "dax_entry_pkey" PRIMARY KEY using index "dax_entry_pkey";

alter table "public"."dax_vault" add constraint "dax_vault_pkey" PRIMARY KEY using index "dax_vault_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_created_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.created_at IS NULL THEN
        NEW.created_at = CURRENT_TIMESTAMP;
    END IF;
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_created_at_with_updated()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.created_at IS NULL THEN
        NEW.created_at = CURRENT_TIMESTAMP;
    END IF;
    IF NEW.updated_at IS NULL THEN
        NEW.updated_at = CURRENT_TIMESTAMP;
    END IF;
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$function$
;

grant delete on table "public"."dax_entry" to "anon";

grant insert on table "public"."dax_entry" to "anon";

grant references on table "public"."dax_entry" to "anon";

grant select on table "public"."dax_entry" to "anon";

grant trigger on table "public"."dax_entry" to "anon";

grant truncate on table "public"."dax_entry" to "anon";

grant update on table "public"."dax_entry" to "anon";

grant delete on table "public"."dax_entry" to "authenticated";

grant insert on table "public"."dax_entry" to "authenticated";

grant references on table "public"."dax_entry" to "authenticated";

grant select on table "public"."dax_entry" to "authenticated";

grant trigger on table "public"."dax_entry" to "authenticated";

grant truncate on table "public"."dax_entry" to "authenticated";

grant update on table "public"."dax_entry" to "authenticated";

grant delete on table "public"."dax_entry" to "service_role";

grant insert on table "public"."dax_entry" to "service_role";

grant references on table "public"."dax_entry" to "service_role";

grant select on table "public"."dax_entry" to "service_role";

grant trigger on table "public"."dax_entry" to "service_role";

grant truncate on table "public"."dax_entry" to "service_role";

grant update on table "public"."dax_entry" to "service_role";

grant delete on table "public"."dax_vault" to "anon";

grant insert on table "public"."dax_vault" to "anon";

grant references on table "public"."dax_vault" to "anon";

grant select on table "public"."dax_vault" to "anon";

grant trigger on table "public"."dax_vault" to "anon";

grant truncate on table "public"."dax_vault" to "anon";

grant update on table "public"."dax_vault" to "anon";

grant delete on table "public"."dax_vault" to "authenticated";

grant insert on table "public"."dax_vault" to "authenticated";

grant references on table "public"."dax_vault" to "authenticated";

grant select on table "public"."dax_vault" to "authenticated";

grant trigger on table "public"."dax_vault" to "authenticated";

grant truncate on table "public"."dax_vault" to "authenticated";

grant update on table "public"."dax_vault" to "authenticated";

grant delete on table "public"."dax_vault" to "service_role";

grant insert on table "public"."dax_vault" to "service_role";

grant references on table "public"."dax_vault" to "service_role";

grant select on table "public"."dax_vault" to "service_role";

grant trigger on table "public"."dax_vault" to "service_role";

grant truncate on table "public"."dax_vault" to "service_role";

grant update on table "public"."dax_vault" to "service_role";


  create policy "Allow authenticated users to delete dax_entry"
  on "public"."dax_entry"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Allow authenticated users to insert dax_entry"
  on "public"."dax_entry"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Allow authenticated users to read dax_entry"
  on "public"."dax_entry"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Allow authenticated users to update dax_entry"
  on "public"."dax_entry"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Allow authenticated users to delete dax_vault"
  on "public"."dax_vault"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Allow authenticated users to insert dax_vault"
  on "public"."dax_vault"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Allow authenticated users to read dax_vault"
  on "public"."dax_vault"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Allow authenticated users to update dax_vault"
  on "public"."dax_vault"
  as permissive
  for update
  to authenticated
using (true)
with check (true);


CREATE TRIGGER set_dax_entry_timestamps BEFORE INSERT ON public.dax_entry FOR EACH ROW EXECUTE FUNCTION public.handle_created_at_with_updated();

CREATE TRIGGER update_dax_entry_timestamp BEFORE UPDATE ON public.dax_entry FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_dax_vault_timestamp BEFORE INSERT ON public.dax_vault FOR EACH ROW EXECUTE FUNCTION public.handle_created_at();


