BEGIN;
--
-- Create model Vault
--
CREATE TABLE "dax_vault" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(255) NOT NULL, "settings" jsonb NOT NULL, "created_at" timestamp with time zone NOT NULL, "owner_id" integer NOT NULL);
--
-- Create model Entry
--
CREATE TABLE "dax_entry" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "heading" varchar(255) NOT NULL, "body" text NOT NULL, "attributes" jsonb NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "vault_id" bigint NOT NULL);
--
-- Create model VaultUser
--
CREATE TABLE "dax_vault_user" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" integer NOT NULL, "vault_id" bigint NOT NULL);
--
-- Add field contributors to vault
--
-- (no-op)
--
-- Create constraint unique_vault_user on model vaultuser
--
ALTER TABLE "dax_vault_user" ADD CONSTRAINT "unique_vault_user" UNIQUE ("vault_id", "user_id");
ALTER TABLE "dax_vault" ADD CONSTRAINT "dax_vault_owner_id_ea8b7b39_fk_auth_user_id" FOREIGN KEY ("owner_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "dax_vault_owner_id_ea8b7b39" ON "dax_vault" ("owner_id");
ALTER TABLE "dax_entry" ADD CONSTRAINT "dax_entry_vault_id_6b1d73eb_fk_dax_vault_id" FOREIGN KEY ("vault_id") REFERENCES "dax_vault" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "dax_entry_vault_id_6b1d73eb" ON "dax_entry" ("vault_id");
ALTER TABLE "dax_vault_user" ADD CONSTRAINT "dax_vault_user_user_id_41d6f09a_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "dax_vault_user" ADD CONSTRAINT "dax_vault_user_vault_id_f0e1679e_fk_dax_vault_id" FOREIGN KEY ("vault_id") REFERENCES "dax_vault" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "dax_vault_user_user_id_41d6f09a" ON "dax_vault_user" ("user_id");
CREATE INDEX "dax_vault_user_vault_id_f0e1679e" ON "dax_vault_user" ("vault_id");
COMMIT;